### ISSUE TITLE
Throw an error when the size of a generated digest256 list does not exceeds Firefox's maximum chunk size

### ISSUE THREAD

**Issue by englehardt** [mozilla-services/shavar-list-creation#104]
See https://github.com/mozilla-services/shavar-prod-lists/pull/79#issuecomment-547186843 for the problems that can result from not doing this. This max chunk size is given [here](https://searchfox.org/mozilla-central/rev/11d9c7b7fa82fdfb8ac2a8f0864e9d8d5fe2b926/toolkit/components/url-classifier/ProtocolParser.cpp#33), and enforced [here](https://searchfox.org/mozilla-central/rev/11d9c7b7fa82fdfb8ac2a8f0864e9d8d5fe2b926/toolkit/components/url-classifier/ProtocolParser.cpp#252).

**Comment by groovecoder** [comment]
This can be marked as fixed now?

**Comment by skim1102** [comment]
Not yet, I need to refactor the code so that it exits before publishing at all. I conveyed that with @englehardt and will remove this as a blocker for #109

**Comment by shreyagupta30** [comment]
Hi @skim1102 Can I work on this?

**Comment by skim1102** [comment]
Hey @shreyagupta30! Just checking on the status of this issue. Do you need anything clarified or have questions on the implementation for fixing this issue?

**Comment by shreyagupta30** [comment]
Yes, ma'am! I am still not able to figure out how to get started here. :(

**Comment by skim1102** [comment]
As discussed on this [comment](https://github.com/mozilla-services/shavar-list-creation/pull/107/files#r358298841) the assertion for the max size should differ based on what version the branch is using.

- for versions equal to or higher than 73 the max size is 4 mebibytes as mentioned in [bug 1594497](https://bugzilla.mozilla.org/show_bug.cgi?id=1594497)
- for versions equal to or lower than 72 the max size is 1 mebibytes

**Comment by shreyagupta30** [comment]
> As discussed on this [comment](https://github.com/mozilla-services/shavar-list-creation/pull/107/files#r358298841) the assertion for the max size should differ based on what version the branch is using.
> 
>     * for versions equal to or higher than 73 the max size is 4 mebibytes as mentioned in [bug 1594497](https://bugzilla.mozilla.org/show_bug.cgi?id=1594497)
> 
>     * for versions equal to or lower than 72 the max size is 1 mebibytes

Looking into it.
